sudo: required
services:
  - docker
before_install:
  - docker build -t test -f Dockerfile.dev .
script:
  - docker run -e CI=true test npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-us-east-2-515145489921"
  bucket_path: "test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
